# Following config is an example to train a periodic wavefunction using transferable atomic orbitals
# across twists, supercell sizes and lattice constants.

experiment_name: transferable_pretraining

### Database name of systems we calculated:
# Graphene 2x2: deepsolid_benchmarks_C_graphene_2x2x1_19twists
# LiH 2x2x2: deepsolid_benchmarks_LiH_fcc_2x2x2_8geoms_10twists_corrected 
# LiH 3x3x3: deepsolid_benchmarks_LiH_fcc_3x3x3_1geoms_10twists_corrected
# HChain: HChainPBC_4-22_1.80_4kgrid or HChainPBC_4-22_1.80_Gamma or HChainPBC12-20_1.20-3.60_120geoms_8kgrid or HChainPBC40_1.20-3.60_88geoms_20kgrid

physical: deepsolid_benchmarks_LiH_fcc_2x2x2_8geoms_10twists_corrected 

pre_training:
  n_epochs: 5000
  mcmc:
    n_burn_in: 5000
    n_inter_steps: 20
    stepsize_update_interval: 100
  sampling_density: reference

optimization:
  n_epochs: 200000
  optimizer:
    learning_rate: 0.1
    norm_constraint: 0.001
    damping: 0.001 # For Graphene we increased to: 0.003
  mcmc:
    n_walkers: 2048
    n_inter_steps: 20 # Potentially you want to increase for systems like Graphene
    n_burn_in: 1000
  clipping:
    name: hard
    center: median
    width_metric: mae
  shared_optimization:
    scheduling_method: weight
  checkpoints:
    keep_every_n_epochs: 5000

evaluation:
  opt_epochs: []
  evaluate_final: true

model:
  name: moon
  features:
    name: moon
    include_twist: [el_el, el_ion]
  embedding:
    name: moon
    envelope_power_output: 2
    initial_scale_output: 10
    el_ion_dim_collect: 128
    ion_dim: 128
    output_dim: 64
  complex_wf: true
  orbitals:
    envelope_orbitals:
    transferable_atomic_orbitals:
      mlp:
        activation: relu
        use_residual: true
        use_layer_norm: true
      envelope_width: 32
      envelope_depth: 2
      backflow_width: 128
      backflow_depth: 2
      use_el_ion_embedding: true
      use_exponentials: true
      use_atom_positions: true
      use_orbital_positions: true
      use_atom_orbital_diff: true
      twist_encoding: [concat, periodic]
    n_determinants: 8
    determinant_schema: full_det
  use_el_el_cusp_correction: true
  jastrow:
    use: true

baseline:
  name: periodic_hf
  basis_set: cc-pVDZ
  localization: boys
  pyscf_options:
    exp_to_discard: 0.1


### Please define your settings here: 
# computation:
  # RESOURCES

# dispatch:
  # RESOURCES

#logging:
#  wandb:
#    project: PROJECT_NAME
#    entity: ENTITY_NAME
