experiment_name: reuse

physical: TinyMol_CNO_rot_dist_C3H4_smiles_C=C=C_test_10geoms

reuse:
  mode: reuse
  path:

optimization:
  n_epochs: 0
  optimizer:
    damping: 0.001
    learning_rate: 0.1
    lr_schedule:
      decay_time: 6000
      offset_time: 32000
  mcmc:
    n_walkers: 2048
    n_inter_steps: 50
    n_burn_in: 16000

  clipping:
    name: hard
    center: median
    width_metric: mae
  checkpoints:
    additional_n_epochs: [1000]
    keep_every_n_epochs: 4000
    replace_every_n_epochs: 4000

evaluation:
  n_epochs: 500
  mcmc:
    n_walkers: 1500
    n_inter_steps: 50
    n_burn_in: 16000

model:

pre_training:
  n_epochs: 0

logging:
  basic:
    n_skip_epochs: 0