

experiment_name: dpe
physical:
  name: C
  R:
  - [0.0, 0.0, 0.0]
  Z: [6]
  n_up: 3

optimization:
  n_epochs: 10_000
  mcmc:
    n_walkers: 2048
    n_inter_steps: 20
    n_burn_in: 1000
  clipping:
    name: hard
    center: median
    width_metric: mae
  checkpoints:
    keep_every_n_epochs: 10000

evaluation:
  n_epochs: 500
model:
  name: dpe4
  embedding:
    name: dpe4
    use_h_two_same_diff: true
    use_w_mapping: true
    emb_dim: 32
    n_hidden_one_el: 256
    n_hidden_two_el: 32
    n_hidden_el_ions: 32
    n_iterations: 4
  orbitals:
    envelope_orbitals:
      initialization: constant
  features:
    concatenate_el_ion_features: false
    n_el_ion_features: 32
    init_with_el_ion_feat: True
    use_el_el_differences: false
    coordinates: cartesian

pre_training:
  n_epochs: 2000
  sampling_density: reference
  mcmc:
    n_inter_steps: 20
    stepsize_update_interval: 10
    initialization: exponential
  off_diagonal_mode: exponential
  off_diagonal_scale: 0.05
  off_diagonal_exponent: 3.0

baseline:
  basis_set: default:6-31G__H:6-31G**
  localization: boys

logging:
  basic:
    n_skip_epochs: 0