name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
            python-version: "${{ matrix.python-version }}"
            cache: "pip"
            cache-dependency-path: '**/requirements*.txt'
      - name: Run CI tests
        run: bash test.sh
        shell: bash
